### ISSUE TITLE
What is what?

### ISSUE THREAD

**Issue by jc5706** [changwoolee/lenet5_hls#9]
Hi Chang,
I'd like to reuse this work on Zynq, but I'm struggling with what's here, I can see the HLS files (no Vivado project though) and some C/C++ files but I'm not sure which ones are Visual Studio and which ones are for the Zynq Processor... Do you have any notes about it?

**Comment by changwoolee** [comment]
Hi jc5706,
the files and directories **except** Win10TestApp&Win10TestAppRelease should be imported to vivado hls or xilinx SDSoC(SDx). 

For HLS syntehsis, this project only supports convolutional layers.
The functions in lenet5/hw_layers/image_convolution.cpp, CONVOLUTION_LAYER_1 to CONVOLUTION_LAYER_3 are the top-level hardware functions in the HLS or SDSoC project.

Other functions in lenet5/hw_layers are not optimized for HLS synthesis because I didn't need them for my project... I used pooling layers and fc layers without synthesis and just run them on PS.
So if you want to synthesize these functions like pooling layers and fully connected layers, the extra work for optimization is needed.



Win10TestApp/Lenet5 Test is a Visual Studio Project and written in C#, so you don't need to import them to vivado project.

I hope that this work help your project :)

**Comment by jc5706** [comment]
Thanks, I'll follow these directions
